### ISSUE TITLE
Tensorflow Model Not Found

### ISSUE THREAD

**Issue by cbstryker** [kinhong/OpenLabeler#1]
I'm getting an error when trying to use inference:

SEVERE  com.easymobo.openlabeler.tensorflow.ObjectDetector: Unable to update null 
org.tensorflow.TensorFlowException: Could not find SavedModel .pb or .pbtxt at supplied export directory path: /opt/model

I have a working .pb file and .pbtxt file in the specified location. The specified directory and files have the correct permissions.

**Comment by kinhong** [comment]
@cbstryker, the Saved Mode Location should be the _**folder**_ where the .pb file is located. If it is at `/opt/model/saved_model/saved_model.pb`, then the location should be specified as `/opt/model/saved_model`. Also, the .pb file must be named _**saved_model.pb**_

**Comment by cbstryker** [comment]
@kinhong yes, I have it working now. Thank you. I recommend writing clear instructions in the Inference tab as it wasn't clear what I needed to do. This would definitely help new users to set up the inferencing on their own.

**Comment by kinhong** [comment]
@cbstryker thanks for your feedback. I have added instructions in the README for the Inference tab.
