### ISSUE TITLE
Creating Custom model using OpenLabeler Training Suport on Windows 10

### ISSUE THREAD

**Issue by alexperezfdz** [kinhong/OpenLabeler#12]
We are using OpenLabeler Training Support to create a custom object detection based on a pretrained model. 

OpenLabeler in Windows 10, Docker, and containers has been put in place following the instructions.
The containers has been verified through the Docker Dashboard.
We use a sample config file from ssd_mobilenet_v2 pretrained model. 

Starting train, a message alert appear indicating "train has started": 
![image](https://user-images.githubusercontent.com/60509387/73560049-8d7ee000-4456-11ea-89c3-c0932ef36741.png)

Nothing happen after close the alert and we have a log showing "unable to train": 

2020-01-31 17:43:05 INFO    com.easymobo.openlabeler.OpenLabeler: OpenLabeler 1.2.1 
2020-01-31 17:43:08 INFO    com.easymobo.openlabeler.tensorflow.ObjectDetector: TensorFlow: 1.15.0 
2020-01-31 17:45:13 INFO    com.easymobo.openlabeler.tensorflow.TFTrainer: Created C:\temp\zzzcoco\data\label_map.pbtxt 
2020-01-31 17:45:13 INFO    com.easymobo.openlabeler.tensorflow.TFTrainer: Creating training data in C:\temp\zzzcoco\data... 
2020-01-31 17:45:13 INFO    com.easymobo.openlabeler.tensorflow.TFRecordCreator: Created train/eval records in C:\temp\zzzcoco\data 
2020-01-31 17:45:13 INFO    com.easymobo.openlabeler.tensorflow.TFTrainer: Created training data in C:\temp\zzzcoco\data 
2020-01-31 17:49:26 INFO    com.easymobo.openlabeler.tensorflow.TFTrainer: Created C:\temp\zzzcoco\data\label_map.pbtxt 
2020-01-31 17:49:26 INFO    com.easymobo.openlabeler.tensorflow.TFTrainer: Created C:\temp\zzzcoco\models\ssd_mobilenet_v2\model.config 
2020-01-31 17:49:27 SEVERE  com.easymobo.openlabeler.tensorflow.TFTrainer: Unable to train 
javax.ws.rs.ProcessingException
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:287)
	at org.glassfish.jersey.client.  ....

The Docker train  preferences: 
![image](https://user-images.githubusercontent.com/60509387/73559862-295c1c00-4456-11ea-88ee-7c2fd4fd255c.png)

 Could you please indicate us what is wrong?

**Comment by kinhong** [comment]
@alexperezfdz - please paste the entire stack trace of the  `2020-01-31 17:49:27 SEVERE` log event, or upload the log file for me to look into it further.

**Comment by alexperezfdz** [comment]
[log.zip](https://github.com/kinhong/OpenLabeler/files/4147247/log.zip)

Hello @kinhong . Here enclosed entier application event log, the model.config created file, and some images about the model folders structure, openlabeler train preferences and docker dashboard showing the gpu container running. 

thanks for your support, 
alex

**Comment by kinhong** [comment]
@alexperezfdz - it looks like [docker-java](https://github.com/docker-java/docker-java) (the library OpenLabeler uses to communicate with docker services) is not able to create Unix sockets on Windows. I think we can get around this by:

1. Upgrading to [OpenLabeler v1.2.2](https://github.com/kinhong/OpenLabeler/releases/tag/v1.2.2) - to get around a Bind#parse bug in [docker-java](https://github.com/docker-java/docker-java) 
2. Open Docker > Settings > General and check "Expose daemon on tcp://localhost:2375 without TLS"

![image](https://user-images.githubusercontent.com/47757221/73703278-3ec68580-46a4-11ea-9537-191ffa26f003.png)

3. Create a <home>\.docker-java.properties file. Add a DOCKER_HOST=tcp://localhost:2376 entry. See [reference](https://github.com/docker-java/docker-java)

4. Restart Docker Desktop/service in Windows

5. Launch OpenLabeler and start training

**Comment by alexperezfdz** [comment]
@kinhong our error persist after perform the modifications. Find enclosed the log:
[log0_custom_ssd.log](https://github.com/kinhong/OpenLabeler/files/4164158/log0_custom_ssd.log)
However, we have some questions: 
- The DOCKER_HOST port should be the encrypted default 2376?   
- We should to run openlabeler container before start training? for example:  docker run -it -d --name OpenLabeler-Trainer -p 2375:2375 kinhong/openlabeler:latest-py3
- Could you please provide us the exact paht where the  .docker-java.properties sould be created? 
- In OpenLabeler Container Host Name train preference we shoud to put just "localhost"?  

thanks in advance for your support.

alex

**Comment by kinhong** [comment]
@alexperezfdz You are getting the same error, that means, at least, the settings in `.docker-java.properties` have not been picked up by the docker-java library. This file should reside under your user-home directory (on Windows 10, it is usually `c:\Users\<username>`), the same place  as the `.openlabeler` directory.

The DOCKER_HOST port should be 2375 (sorry for the typo earlier).

There is no need to run the container before Start Training. OpenLabeler will run the container using the docker-java library.

**Comment by alexperezfdz** [comment]
@kinhong works fine! thanks for your support and your excelent job!
