### ISSUE TITLE
Ellipse and polygon detection

### ISSUE THREAD

**Issue by lrlunin** [kinhong/OpenLabeler#14]
Hello. I'm very impressed by your program. What do you think about adding selection figures like the ellipse and maybe a polygon? I would be happy to spend a few weeks (or maybe months) on adding such functionality if it were appropriate.

**Comment by kinhong** [comment]
@lrlunin You are most welcome to contribute! Are you thinking of adding COCO JSON format support to OpenLabeler? Another user, @beckstev, has also requested [similar features].(https://github.com/kinhong/OpenLabeler/issues/2#issuecomment-487400579)

**Comment by veonua** [comment]
@lrlunin 
an ellipse would not improve the result as the majority of models are based on ConvNets that have rectangular inputs.
at this moment there are three types of models - object detection (rectangles) and segmentation (bitmap), and key-point based
