### ISSUE TITLE
Any plans to support Tensorflow 2?

### ISSUE THREAD

**Issue by veonua** [kinhong/OpenLabeler#17]
Object detection API has been updated to run on the latest TF version,
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

it seems like output vector has been replaced with a dictionary, at least in my code I had to replace 

```
num_detections = result[0].numpy()
classes = result[1].numpy()
```

to 

```
num_detections = result["num_detections"].numpy()
classes = result['detection_classes'].numpy()

```

**Comment by kinhong** [comment]
@veonua I am still waiting for a more official release of TensorFlow 2.0 Java API (I have been following [this issue](https://github.com/tensorflow/tensorflow/issues/32943))

**Comment by veonua2** [comment]
> References:
> https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-2.3.0.jar
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow_jni-cpu-linux-x86_64-2.3.0.tar.gz
https://www.tensorflow.org/install/lang_java

looks promising, but I am not fully aware of set of jars required to run it on Java, I assume update of protobuf would be good enough to run inference.

**Comment by kinhong** [comment]
@veonua2 In release [v1.3.0](https://github.com/kinhong/OpenLabeler/releases/tag/v1.3.0), OpenLabeler now supports TensorFlow 2.3.1.

**Comment by veonua** [comment]
thank you very much
