### ISSUE TITLE
Training not detecting model type or docker process (MacOS)

### ISSUE THREAD

**Issue by 4down** [kinhong/OpenLabeler#18]
MacOS (Big Sur) - I was running a prior version of OpenLabeler and updated to 1.3.0.  Before updating, I had configured the training tab and it was correctly displaying model type and was picking up my Docker process, and allowed me to continue/start training.  

After updating, there is nothing showing next to Model Type, Last Trained Checkpoint, and Docker Process, and the buttons do not appear.

I've deleted the Base Model Directory and applied that, then re-opened preferences to enter the path again to re-apply, and nothing changes.  Not sure what I could attempt to affect its ability to detect the docker process.

Thanks!

**Comment by kinhong** [comment]
@spencer-strickland-fourdown I just did a quick test, things seem to be working for me (I am on macOS Catalina). Note that 1.3.0 integrates with TF 2.x; so only models from [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) are supported.

To further diagnose, I'd suggest:
1. Examine the logs under ~/.openlabeler/logs
2. Examine the logs of the docker process: `docker logs -f <container_id>`
