### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by currychris** [kinhong/OpenLabeler#19]
After installation on Windows 10 using the .msi from the releases page I get the error "failed to launch JVM".
Tried this on multiple machines and multiple jdks.

**Comment by kinhong** [comment]
Hmm... I was able to install and run version 1.3 on Windows 10. OpenLabeler uses its bundled JVM (version 15). Does the application log (under <home>\.openlabeler\logs) show anything errors?

**Comment by currychris** [comment]
I cannot find the application log folder. The only OpenLabeler folder I do find is under (C:\Program Files\OpenLabeler), but there are on logs in there

**Comment by kinhong** [comment]
Have you looked under your [user-home]\.openlabeler\logs directory?

**Comment by currychris** [comment]
I have. There is no .openlabeler folder in my home directory unfortunately.

**Comment by kinhong** [comment]
Could you post a screenshot of the exact failure?

**Comment by currychris** [comment]
![error](https://user-images.githubusercontent.com/38907412/127534149-c385eb34-325a-4aea-a342-a763c3a9ace8.PNG)

**Comment by kinhong** [comment]
Do you happened to have the Java Access Bridge installed on your machine

**Comment by currychris** [comment]
Yes, I have it installed and enabled

**Comment by kinhong** [comment]
Could you please disable JAB and try launching OpenLabeler again?

**Comment by currychris** [comment]
I have tried that but it made no difference unfortunately

**Comment by kinhong** [comment]
I am assuming you can install/run other java programs without problem. I would suggest cloning and building this project, then running it using the Windows command prompt. Hopefully, you will get more diagnostic information.
