### ISSUE TITLE
How to run OpenLabeler 

### ISSUE THREAD

**Issue by beckstev** [kinhong/OpenLabeler#2]
Hi, 

I have followed your installation, however I dont know how to run OpenLabeler. 

Best regards, 

Steven

**Comment by kinhong** [comment]
Hi @beckstev - on which OS did you install OpenLabeler on?

**Comment by beckstev** [comment]
Hi @kinhong, Ubuntu 18

**Comment by kinhong** [comment]
@beckstev, the easiest way is to first click on the "Applications" button, normally found on the lower left corner of your desktop (the button with the 3x3 dots icon), then the OpenLabeler icon could be found there (or you can search for it). Let me know if this helps.

**Comment by beckstev** [comment]
Yes it is working now, thanks! I forgot to run the .deb file.
Frankly, OpenLabeler is the most polished freeware solution I have tested so far. Good job!

Do you plan to implement the following features:

- export just a single label file which contains all the labels
- .json support
- polygone labeling
- some kind of project file to relabel images

**Comment by kinhong** [comment]
@beckstev, thanks for your feedback.

> Do you plan to implement the following features?:
> 
> * export just a single label file which contains all the labels
> * .json support
> * polygone labeling
> * some kind of project file to relabel images

Yes, those are in the works.
