### ISSUE TITLE
different box colors for different labels

### ISSUE THREAD

**Issue by Lotti** [kinhong/OpenLabeler#3]
Hello!

I want to sugget a feature: use different color (random generated?) for each label! 
In this way is easier to understand what is tagged and which label is used.

Thank you for your work.

**Comment by kinhong** [comment]
@Lotti That sounds like a good idea. I will incorporate it in my next update.

Thanks for your feedback.

**Comment by kinhong** [comment]
I have added this feature in release v1.2.0

**Comment by Lotti** [comment]
thank you! I'm downloading the new release ;)
