### ISSUE TITLE
Getting error on executing jar file no main manifest attribute

### ISSUE THREAD

**Issue by murali513** [kinhong/OpenLabeler#6]
Getting error on executing jar file no main manifest attribute.
Please let me know what are the next steps to open tool.
after mvn clean install..
Whats next step

**Comment by kinhong** [comment]
@murali513, after the build, the OS-specific installers can be found under the app/target/package directory. You will then need to run the installers.

**Comment by murali513** [comment]
@kinhong, 
thanks you for your response above. I am new the java environment.
Now getting error when install .deb pkg
 I am using ubuntu so i can run the below command:
sudo apt install ../openlabeler-0.0.0.deb
Getting below error:
Adding shortcut to the menu
/var/lib/dpkg/info/openlabeler.postinst: 25: /var/lib/dpkg/info/openlabeler.postinst: xdg-desktop-menu: not found
dpkg: error processing package openlabeler (--install):
 installed openlabeler package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 openlabeler

**Comment by murali513** [comment]
above issue resolved by using the below command:
sudo apt-get install -y xdg-utils

**Comment by kinhong** [comment]
@murali513 - OK, good to know.

I usually just double-click the .deb file or use the command "sudo dpkg -i <filename>.deb" to install.
