### ISSUE TITLE
Can you give me Linux comman using YUM package for installation

### ISSUE THREAD

**Issue by murali513** [kinhong/OpenLabeler#7]
Can you give me Linux commands using YUM package for installation

**Comment by kinhong** [comment]
You might want to try the commands [here](https://linuxconfig.org/how-to-install-deb-file-in-redhat-linux-8). I have never tried them, though. Let us know if they work.

**Comment by murali513** [comment]
How can check the current model training status? like where or how to check the logs of model training?
