### ISSUE TITLE
How to check current model training status?

### ISSUE THREAD

**Issue by murali513** [kinhong/OpenLabeler#8]
I have started training on model ,but there is no updates on model folder.
Is it some where need to check. Pls guid me how to train model

**Comment by kinhong** [comment]
@murali513 - Are you using OpenLabeler to train? OpenLabeler communicates with a docker container to obtain a coarse-grained training status (i.e. if the container is still running so one can start or stop the docker container) and attempts to update the training checkpoint number.

Currently, as an experimental feature, the "Train (experimental)" category pane of the Preferences dialog is the only interface available to manage TensorFlow training.
