### ISSUE TITLE
View features are not working in Windows 10

### ISSUE THREAD

**Issue by tariqrahiman** [kinhong/OpenLabeler#9]
View features are not working in Windows 10
File > View > Zoom in, out, Rotate Hints etc is not working in the latest windows installer
![ol-1-view](https://user-images.githubusercontent.com/913554/71327242-09caee80-24bb-11ea-8813-e5eb120f837a.PNG)

**Comment by kinhong** [comment]
@tariqrahiman - the View -> Zoom in, out, etc. features are working for me under Windows 10 for version 1.2.0. Are they not working for you on a particular image?

**Comment by tariqrahiman** [comment]
going to test release 1.2.1 tonight and will let you know the results. I might have messed up with the installation steps.

**Comment by tariqrahiman** [comment]
@kinhong Is there an updated Win 10 version ?

**Comment by kinhong** [comment]
> @kinhong Is there an updated Win 10 version?

I have just published v1.4.0 on all three OS platforms
